/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import domain.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tognere
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        lbUser.setText("Bem Vindo "+Usuario.logado.getNome());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUser = new javax.swing.JLabel();
        lbWallpaper = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCliente = new javax.swing.JMenu();
        miClienteCadastrar = new javax.swing.JMenuItem();
        miClienteVisualizar = new javax.swing.JMenuItem();
        mUsuario = new javax.swing.JMenu();
        miUsuarioCadastrar = new javax.swing.JMenuItem();
        mImovel = new javax.swing.JMenu();
        mFormaPagamento = new javax.swing.JMenu();
        mVenda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imobiliária Marvi");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(680, 800));
        getContentPane().setLayout(null);
        getContentPane().add(lbUser);
        lbUser.setBounds(20, 10, 60, 20);

        lbWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(lbWallpaper);
        lbWallpaper.setBounds(-30, -50, 770, 760);

        mCliente.setText("Cliente");

        miClienteCadastrar.setText("Cadastrar");
        miClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteCadastrarActionPerformed(evt);
            }
        });
        mCliente.add(miClienteCadastrar);

        miClienteVisualizar.setText("Visualizar");
        miClienteVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteVisualizarActionPerformed(evt);
            }
        });
        mCliente.add(miClienteVisualizar);

        jMenuBar1.add(mCliente);

        mUsuario.setText("Usuario");

        miUsuarioCadastrar.setText("Cadastrar");
        miUsuarioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioCadastrarActionPerformed(evt);
            }
        });
        mUsuario.add(miUsuarioCadastrar);

        jMenuBar1.add(mUsuario);

        mImovel.setText("Imóvel");
        jMenuBar1.add(mImovel);

        mFormaPagamento.setText("Forma de Pagamento");
        jMenuBar1.add(mFormaPagamento);

        mVenda.setText("Venda");
        jMenuBar1.add(mVenda);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 750, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void miClienteVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteVisualizarActionPerformed
        FrmClienteVisualizar visualizarCliente = new FrmClienteVisualizar();
        visualizarCliente.setVisible(true);
    }//GEN-LAST:event_miClienteVisualizarActionPerformed

    private void miClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteCadastrarActionPerformed
        try {
            FrmCliente cliente = new FrmCliente();
            cliente.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miClienteCadastrarActionPerformed

    private void miUsuarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioCadastrarActionPerformed
        if (Usuario.logado.getAcesso().equals("admin")) {
            FrmUsuario usuario = new FrmUsuario();
            usuario.setVisible(true);
        }

    }//GEN-LAST:event_miUsuarioCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbWallpaper;
    private javax.swing.JMenu mCliente;
    private javax.swing.JMenu mFormaPagamento;
    private javax.swing.JMenu mImovel;
    private javax.swing.JMenu mUsuario;
    private javax.swing.JMenu mVenda;
    private javax.swing.JMenuItem miClienteCadastrar;
    private javax.swing.JMenuItem miClienteVisualizar;
    private javax.swing.JMenuItem miUsuarioCadastrar;
    // End of variables declaration//GEN-END:variables
}
