/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import domain.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author victor alves abreu
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        lbUser.setText("Bem Vindo " + Usuario.logado.getNome());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUser = new javax.swing.JLabel();
        lbWallpaper = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        mCliente = new javax.swing.JMenu();
        miClienteCadastrar = new javax.swing.JMenuItem();
        miClienteVisualizar = new javax.swing.JMenuItem();
        mUsuario = new javax.swing.JMenu();
        miUsuarioCadastrar = new javax.swing.JMenuItem();
        miUsuarioVisualizar = new javax.swing.JMenuItem();
        mImovel = new javax.swing.JMenu();
        miImovelCadastrar = new javax.swing.JMenuItem();
        miImovelVisualizar = new javax.swing.JMenuItem();
        mVenda = new javax.swing.JMenu();
        miVendaCadastrar = new javax.swing.JMenuItem();
        miVendaVisualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imobiliária Marvi");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(680, 800));
        getContentPane().setLayout(null);
        getContentPane().add(lbUser);
        lbUser.setBounds(20, 10, 230, 20);

        lbWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(lbWallpaper);
        lbWallpaper.setBounds(-30, -50, 770, 760);

        mCliente.setText("Cliente");

        miClienteCadastrar.setText("Cadastrar");
        miClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteCadastrarActionPerformed(evt);
            }
        });
        mCliente.add(miClienteCadastrar);

        miClienteVisualizar.setText("Visualizar");
        miClienteVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteVisualizarActionPerformed(evt);
            }
        });
        mCliente.add(miClienteVisualizar);

        mbPrincipal.add(mCliente);

        mUsuario.setText("Usuario");

        miUsuarioCadastrar.setText("Cadastrar");
        miUsuarioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioCadastrarActionPerformed(evt);
            }
        });
        mUsuario.add(miUsuarioCadastrar);

        miUsuarioVisualizar.setText("Visualizar");
        miUsuarioVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioVisualizarActionPerformed(evt);
            }
        });
        mUsuario.add(miUsuarioVisualizar);

        mbPrincipal.add(mUsuario);

        mImovel.setText("Imóvel");

        miImovelCadastrar.setText("Cadastrar");
        miImovelCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImovelCadastrarActionPerformed(evt);
            }
        });
        mImovel.add(miImovelCadastrar);

        miImovelVisualizar.setText("Visualizar");
        miImovelVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImovelVisualizarActionPerformed(evt);
            }
        });
        mImovel.add(miImovelVisualizar);

        mbPrincipal.add(mImovel);

        mVenda.setText("Venda");

        miVendaCadastrar.setText("Cadastrar");
        miVendaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVendaCadastrarActionPerformed(evt);
            }
        });
        mVenda.add(miVendaCadastrar);

        miVendaVisualizar.setText("Visualizar");
        miVendaVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVendaVisualizarActionPerformed(evt);
            }
        });
        mVenda.add(miVendaVisualizar);

        mbPrincipal.add(mVenda);

        setJMenuBar(mbPrincipal);

        setBounds(0, 0, 750, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void miClienteVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteVisualizarActionPerformed
        FrmClienteVisualizar visualizarCliente = new FrmClienteVisualizar();
        visualizarCliente.setVisible(true);
    }//GEN-LAST:event_miClienteVisualizarActionPerformed

    private void miClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteCadastrarActionPerformed
        try {
            FrmCliente cliente = new FrmCliente();
            cliente.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miClienteCadastrarActionPerformed

    private void miUsuarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioCadastrarActionPerformed
        if (Usuario.logado.getAcesso().equals("admin")) {
            FrmUsuario usuario = new FrmUsuario();
            usuario.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Voce não possue permição para acessar esse recurso!");
        }

    }//GEN-LAST:event_miUsuarioCadastrarActionPerformed

    private void miImovelCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImovelCadastrarActionPerformed
        FrmImovel imovel = new FrmImovel();
        imovel.setVisible(true);
    }//GEN-LAST:event_miImovelCadastrarActionPerformed

    private void miVendaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVendaCadastrarActionPerformed
        FrmVenda venda;
        try {
            venda = new FrmVenda();
            venda.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_miVendaCadastrarActionPerformed

    private void miUsuarioVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioVisualizarActionPerformed
        if(Usuario.logado.getAcesso().equals("admin"))
        {
            FrmUsuarioVisualizar usuario = new FrmUsuarioVisualizar();
            usuario.setVisible(true);
        }
    }//GEN-LAST:event_miUsuarioVisualizarActionPerformed

    private void miImovelVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImovelVisualizarActionPerformed
        FrmImovelVisualizar imovel = new FrmImovelVisualizar();
        imovel.setVisible(true);
    }//GEN-LAST:event_miImovelVisualizarActionPerformed

    private void miVendaVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVendaVisualizarActionPerformed
        FrmVendaVisualizar venda = new FrmVendaVisualizar();
        venda.setVisible(true);
    }//GEN-LAST:event_miVendaVisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbWallpaper;
    private javax.swing.JMenu mCliente;
    private javax.swing.JMenu mImovel;
    private javax.swing.JMenu mUsuario;
    private javax.swing.JMenu mVenda;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miClienteCadastrar;
    private javax.swing.JMenuItem miClienteVisualizar;
    private javax.swing.JMenuItem miImovelCadastrar;
    private javax.swing.JMenuItem miImovelVisualizar;
    private javax.swing.JMenuItem miUsuarioCadastrar;
    private javax.swing.JMenuItem miUsuarioVisualizar;
    private javax.swing.JMenuItem miVendaCadastrar;
    private javax.swing.JMenuItem miVendaVisualizar;
    // End of variables declaration//GEN-END:variables
}
