/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import crud.ClienteCRUD;
import crud.FormaDePagamentoCRUD;
import javax.swing.JOptionPane;
import crud.UsuarioCRUD;
import domain.Cliente;
import domain.FormaDePagamento;
import domain.Usuario;

/**
 *
 * @author tognere
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miClienteCadastrar = new javax.swing.JMenuItem();
        miClienteVisualizar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miUsuarioCadastrar = new javax.swing.JMenuItem();
        miUsuarioVisualizarTodos = new javax.swing.JMenuItem();
        miUsuarioVisualizar = new javax.swing.JMenuItem();
        miUsuarioEditar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miImovelCadastrar = new javax.swing.JMenuItem();
        miImovelVisualizar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miFormPagamentoCadastrar = new javax.swing.JMenuItem();
        miFormPagamentoVisualizar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miVendaCadastrar = new javax.swing.JMenuItem();
        miVendaVisualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imobiliária Marvi");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(680, 800));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, -50, 770, 760);

        jMenu1.setText("Cliente");

        miClienteCadastrar.setText("Cadastrar");
        miClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(miClienteCadastrar);

        miClienteVisualizar.setText("Visualizar");
        miClienteVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteVisualizarActionPerformed(evt);
            }
        });
        jMenu1.add(miClienteVisualizar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuário");

        miUsuarioCadastrar.setText("Cadastrar");
        miUsuarioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioCadastrarActionPerformed(evt);
            }
        });
        jMenu2.add(miUsuarioCadastrar);

        miUsuarioVisualizarTodos.setText("Visualizar Todos");
        miUsuarioVisualizarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioVisualizarTodosActionPerformed(evt);
            }
        });
        jMenu2.add(miUsuarioVisualizarTodos);

        miUsuarioVisualizar.setText("Visualizar ");
        miUsuarioVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioVisualizarActionPerformed(evt);
            }
        });
        jMenu2.add(miUsuarioVisualizar);

        miUsuarioEditar.setText("Editar");
        miUsuarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioEditarActionPerformed(evt);
            }
        });
        jMenu2.add(miUsuarioEditar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Imóvel");

        miImovelCadastrar.setText("Cadastrar");
        miImovelCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImovelCadastrarActionPerformed(evt);
            }
        });
        jMenu3.add(miImovelCadastrar);

        miImovelVisualizar.setText("Visualizar");
        jMenu3.add(miImovelVisualizar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Forma de Pagamento");

        miFormPagamentoCadastrar.setText("Cadastrar");
        miFormPagamentoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormPagamentoCadastrarActionPerformed(evt);
            }
        });
        jMenu4.add(miFormPagamentoCadastrar);

        miFormPagamentoVisualizar.setText("Visualizar");
        miFormPagamentoVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormPagamentoVisualizarActionPerformed(evt);
            }
        });
        jMenu4.add(miFormPagamentoVisualizar);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Venda");

        miVendaCadastrar.setText("Cadastrar");
        miVendaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVendaCadastrarActionPerformed(evt);
            }
        });
        jMenu5.add(miVendaCadastrar);

        miVendaVisualizar.setText("Visualizar");
        jMenu5.add(miVendaVisualizar);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 750, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void miClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteCadastrarActionPerformed
        FrmCliente obj = new FrmCliente();
        obj.setVisible(true);
    }//GEN-LAST:event_miClienteCadastrarActionPerformed

    private void miUsuarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioCadastrarActionPerformed
        FrmUsuario obj = new FrmUsuario();
        obj.setVisible(true);
    }//GEN-LAST:event_miUsuarioCadastrarActionPerformed

    private void miImovelCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImovelCadastrarActionPerformed
        FrmImovel obj = new FrmImovel();
        obj.setVisible(true);
    }//GEN-LAST:event_miImovelCadastrarActionPerformed

    private void miFormPagamentoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormPagamentoCadastrarActionPerformed
        FrmFormaPagamento obj = new FrmFormaPagamento();
        obj.setVisible(true);
    }//GEN-LAST:event_miFormPagamentoCadastrarActionPerformed

    private void miVendaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVendaCadastrarActionPerformed
        FrmVenda obj = new FrmVenda();
        obj.setVisible(true);
    }//GEN-LAST:event_miVendaCadastrarActionPerformed

    private void miUsuarioVisualizarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioVisualizarTodosActionPerformed
        UsuarioCRUD usuario = new UsuarioCRUD();
        String usuarios = "";
        if (usuario.ler().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum Usuario Cadastrado!!");
        } else {
            for (Usuario u : usuario.ler()) {
                usuarios = "";
                usuarios += "Nome: " + u.getNome() + "\n";
                usuarios += "CPF: " + u.getCpf() + "\n";
                usuarios += "Email: " + u.getEmail() + "\n";
                usuarios += "ID: " + u.getId() + "\n\n";
                JOptionPane.showMessageDialog(this, usuarios);
            }
        }
    }//GEN-LAST:event_miUsuarioVisualizarTodosActionPerformed

    private void miUsuarioVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioVisualizarActionPerformed
        UsuarioCRUD user = new UsuarioCRUD();
        if (user.ler().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhim Usuario Cadastrados!!");
        } else {
            JOptionPane.showMessageDialog(this, user.ler(Integer.parseInt(JOptionPane.showInputDialog(this, "Digite o ID do Usuario a ser pesquisado"))));
        }
    }//GEN-LAST:event_miUsuarioVisualizarActionPerformed

    private void miClienteVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteVisualizarActionPerformed
        ClienteCRUD cliente = new ClienteCRUD();
        String clientes = "";
        if (cliente.ler().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum Usuario Cadastrado!!");
        } else {
            for (Cliente u : cliente.ler()) {
                clientes = "";
                clientes += "Nome: " + u.getNome() + "\n";
                clientes += "CPF: " + u.getCpf() + "\n";
                clientes += "Email: " + u.getEmail() + "\n";
                clientes += "Rua: " + u.getRua() + "\n";
                clientes += "Numero: " + u.getNumero() + "\n";        
                clientes += "Cep: " + u.getCep() + "\n";        
                clientes += "Bairro: " + u.getBairro() + "\n";        
                //cliente += "Uf: " + u.getUf() + "\n"
                clientes += "ID: " + u.getId() + "\n\n";
                JOptionPane.showMessageDialog(this, clientes);
            }
        }
    }//GEN-LAST:event_miClienteVisualizarActionPerformed

    private void miFormPagamentoVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormPagamentoVisualizarActionPerformed
        FormaDePagamentoCRUD formaDePagamento = new FormaDePagamentoCRUD();
        String formaDePagamentos = "";
        if (formaDePagamento.ler().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma forma de pagamento Cadastrada!!");
        } else {
            for (FormaDePagamento u : formaDePagamento.ler()) {
                formaDePagamentos = "";
                formaDePagamentos += "Tipo: " + u.getTipo() + "\n";    
                formaDePagamentos += "ID: " + u.getId() + "\n\n";
                JOptionPane.showMessageDialog(this, formaDePagamentos);
            }
        }
    }//GEN-LAST:event_miFormPagamentoVisualizarActionPerformed

    private void miUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioEditarActionPerformed
        FrmCliente editar = new FrmCliente(Integer.parseInt(JOptionPane.showInputDialog(this, "Digite o Id do Cliente a ser alterado")));
    }//GEN-LAST:event_miUsuarioEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miClienteCadastrar;
    private javax.swing.JMenuItem miClienteVisualizar;
    private javax.swing.JMenuItem miFormPagamentoCadastrar;
    private javax.swing.JMenuItem miFormPagamentoVisualizar;
    private javax.swing.JMenuItem miImovelCadastrar;
    private javax.swing.JMenuItem miImovelVisualizar;
    private javax.swing.JMenuItem miUsuarioCadastrar;
    private javax.swing.JMenuItem miUsuarioEditar;
    private javax.swing.JMenuItem miUsuarioVisualizar;
    private javax.swing.JMenuItem miUsuarioVisualizarTodos;
    private javax.swing.JMenuItem miVendaCadastrar;
    private javax.swing.JMenuItem miVendaVisualizar;
    // End of variables declaration//GEN-END:variables
}

